-- =============================================================================
-- SUPER ADMIN SETUP & DATABASE MANAGEMENT RPCs
-- =============================================================================

-- 1. UPDATE PROFILE ROLE CHECK CONSTRAINT
-- Remove existing check constraint if any and replace with updated set including super_admin, moderator, support
ALTER TABLE public.profiles DROP CONSTRAINT IF EXISTS profiles_role_check;
ALTER TABLE public.profiles ADD CONSTRAINT profiles_role_check CHECK (role IN ('user', 'admin', 'super_admin', 'moderator', 'support'));

-- 2. ENHANCE IS_ADMIN() HELPER TO INCLUDE SUPER ADMIN
CREATE OR REPLACE FUNCTION public.is_admin()
RETURNS boolean
LANGUAGE sql
SECURITY DEFINER
STABLE
AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.profiles
    WHERE id = auth.uid() AND (role = 'admin' OR role = 'super_admin')
  );
$$;

-- 2.b FIX BROKEN LOG_AUDIT_EVENT() TRIGGER FUNCTION
-- Safely extracts row ID using JSONB keys for tables lacking a primary 'id' column.
CREATE OR REPLACE FUNCTION public.log_audit_event()
RETURNS trigger AS $$
DECLARE
  v_user_id uuid;
  v_old_data jsonb := null;
  v_new_data jsonb := null;
  v_record_id text := null;
BEGIN
  v_user_id := auth.uid();
  
  IF TG_OP = 'DELETE' THEN
    v_old_data := to_jsonb(OLD);
    v_record_id := COALESCE(
      v_old_data->>'id',
      v_old_data->>'key',
      v_old_data->>'name',
      (v_old_data->>'user_id') || ':' || (v_old_data->>'role_id'),
      'unknown'
    );
  ELSIF TG_OP = 'UPDATE' THEN
    v_old_data := to_jsonb(OLD);
    v_new_data := to_jsonb(NEW);
    v_record_id := COALESCE(
      v_new_data->>'id',
      v_new_data->>'key',
      v_new_data->>'name',
      (v_new_data->>'user_id') || ':' || (v_new_data->>'role_id'),
      'unknown'
    );
  ELSIF TG_OP = 'INSERT' THEN
    v_new_data := to_jsonb(NEW);
    v_record_id := COALESCE(
      v_new_data->>'id',
      v_new_data->>'key',
      v_new_data->>'name',
      (v_new_data->>'user_id') || ':' || (v_new_data->>'role_id'),
      'unknown'
    );
  END IF;

  INSERT INTO public.audit_logs (user_id, action, table_name, record_id, old_data, new_data)
  VALUES (v_user_id, TG_OP, TG_TABLE_NAME, v_record_id, v_old_data, v_new_data);
  
  IF TG_OP = 'DELETE' THEN
    RETURN OLD;
  ELSE
    RETURN NEW;
  END IF;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;


-- 3. EXPAND PROFILE RLS FOR ADMINISTRATIVE ACCESS
DROP POLICY IF EXISTS "profiles_update_admin" ON public.profiles;
CREATE POLICY "profiles_update_admin" ON public.profiles FOR UPDATE
  TO authenticated USING (public.is_admin()) WITH CHECK (public.is_admin());

-- 4. SUPER ADMIN HELPER FUNCTION
CREATE OR REPLACE FUNCTION public.is_super_admin_check()
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
STABLE
AS $$
BEGIN
  RETURN EXISTS (
    SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'super_admin'
  ) OR EXISTS (
    SELECT 1 FROM public.user_roles ur
    JOIN public.app_roles r ON ur.role_id = r.id
    WHERE ur.user_id = auth.uid() AND r.name = 'super_admin'
  );
END;
$$;

-- 5. SECURE ADMIN USER CREATION FUNCTION (Bypasses signUp sign-in replacement)
CREATE OR REPLACE FUNCTION public.admin_create_user(
  user_email text,
  user_password text,
  user_full_name text,
  user_role text
)
RETURNS uuid
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  new_user_id uuid;
BEGIN
  -- Security check: Only Super Admin can invoke
  IF NOT public.is_super_admin_check() THEN
    RAISE EXCEPTION 'Access Denied: Only Super Admins can create administrative users.';
  END IF;

  -- Create record in auth.users
  INSERT INTO auth.users (
    instance_id,
    email,
    encrypted_password,
    email_confirmed_at,
    raw_user_meta_data,
    role,
    aud,
    created_at,
    updated_at
  )
  VALUES (
    '00000000-0000-0000-0000-000000000000',
    user_email,
    extensions.crypt(user_password, extensions.gen_salt('bf')),
    now(),
    jsonb_build_object('full_name', user_full_name),
    'authenticated',
    'authenticated',
    now(),
    now()
  )
  RETURNING id INTO new_user_id;

  -- Update default profile role generated by handle_new_user trigger
  UPDATE public.profiles
  SET role = user_role, full_name = user_full_name
  WHERE id = new_user_id;

  -- Insert into app_roles RBAC table
  INSERT INTO public.user_roles (user_id, role_id)
  SELECT new_user_id, id FROM public.app_roles WHERE name = user_role
  ON CONFLICT DO NOTHING;

  RETURN new_user_id;
END;
$$;

-- 6. SECURE ADMIN USER DELETION FUNCTION (Cascades to profiles and data)
CREATE OR REPLACE FUNCTION public.admin_delete_user(target_user_id uuid)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  -- Security check: Only Super Admin can invoke
  IF NOT public.is_super_admin_check() THEN
    RAISE EXCEPTION 'Access Denied: Only Super Admins can delete users.';
  END IF;

  -- Self-deletion guard
  IF auth.uid() = target_user_id THEN
    RAISE EXCEPTION 'Operation Denied: You cannot delete your own account.';
  END IF;

  -- Delete from auth.users (which cascades to profiles and other dependencies)
  DELETE FROM auth.users WHERE id = target_user_id;
END;
$$;

-- 7. SECURE ADMIN USER PASSWORD RESET
CREATE OR REPLACE FUNCTION public.admin_reset_password(target_user_id uuid, new_password text)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  -- Security check: Only Super Admin can invoke
  IF NOT public.is_super_admin_check() THEN
    RAISE EXCEPTION 'Access Denied: Only Super Admins can reset user passwords.';
  END IF;

  -- Update user password in auth.users
  UPDATE auth.users
  SET encrypted_password = extensions.crypt(new_password, extensions.gen_salt('bf')),
      updated_at = now()
  WHERE id = target_user_id;
END;
$$;

-- 8. AUDIT LOGGING TRIGGERS FOR PROFILES
DROP TRIGGER IF EXISTS audit_profiles ON public.profiles;
CREATE TRIGGER audit_profiles
AFTER INSERT OR UPDATE OR DELETE ON public.profiles
FOR EACH ROW EXECUTE FUNCTION log_audit_event();

-- 9. SEED DEFAULT SYSTEM SETTINGS IF MISSING
INSERT INTO public.system_settings (key, value, updated_at) VALUES
('platform_name', '"ResellBD"'::jsonb, now()),
('commission_rate', '5'::jsonb, now()),
('currency', '"BDT"'::jsonb, now()),
('default_language', '"en"'::jsonb, now()),
('maintenance_mode', 'false'::jsonb, now())
ON CONFLICT (key) DO NOTHING;

-- 10. REVIEWS & MESSAGES RLS FOR ADMIN DELETION
DROP POLICY IF EXISTS "reviews_admin_delete" ON public.reviews;
CREATE POLICY "reviews_admin_delete" ON public.reviews FOR DELETE
  TO authenticated USING (public.is_admin());

DROP POLICY IF EXISTS "messages_admin_delete" ON public.messages;
CREATE POLICY "messages_admin_delete" ON public.messages FOR DELETE
  TO authenticated USING (public.is_admin());

-- 11. ROLE PERMISSIONS MATRIX RLS
DROP POLICY IF EXISTS "Manage role permissions" ON public.role_permissions;
CREATE POLICY "Manage role permissions" ON public.role_permissions FOR ALL
  TO authenticated USING (public.is_admin()) WITH CHECK (public.is_admin());

-- 12. DATABASE CONSOLE METRICS RPC
CREATE OR REPLACE FUNCTION public.get_database_table_stats()
RETURNS TABLE(table_name text, row_count bigint, size_pretty text)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  r record;
  r_count bigint;
BEGIN
  -- Security check: Only Super Admin can invoke
  IF NOT public.is_super_admin_check() THEN
    RAISE EXCEPTION 'Access Denied: Only Super Admins can inspect database status.';
  END IF;

  FOR r IN 
    SELECT t.table_name::text as t_name
    FROM information_schema.tables t
    WHERE t.table_schema = 'public' AND t.table_type = 'BASE TABLE'
  LOOP
    EXECUTE format('SELECT count(*) FROM public.%I', r.t_name) INTO r_count;
    table_name := r.t_name;
    row_count := r_count;
    size_pretty := pg_size_pretty(pg_total_relation_size('public.' || r.t_name))::text;
    RETURN NEXT;
  END LOOP;
END;
$$;



